/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';


export namespace Components {

  interface CurrentBlock {}
  interface CurrentBlockAttributes extends StencilHTMLAttributes {}

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CurrentBlock': Components.CurrentBlock;
    'MyApp': Components.MyApp;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'current-block': Components.CurrentBlockAttributes;
    'my-app': Components.MyAppAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLCurrentBlockElement extends Components.CurrentBlock, HTMLStencilElement {}
  var HTMLCurrentBlockElement: {
    prototype: HTMLCurrentBlockElement;
    new (): HTMLCurrentBlockElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'current-block': HTMLCurrentBlockElement
    'my-app': HTMLMyAppElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'current-block': HTMLCurrentBlockElement;
    'my-app': HTMLMyAppElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
